### ISSUE TITLE
NeedsBrowser

### ISSUE THREAD

**Issue by msebastian100** [onyxbits/raccoon4#110]
Login not possible
Despite correct username & password 

Error: NeedsBrowser

**Comment by dondejhondon** [comment]
@msebastian100 I too encounter the same issue. I want to use my main account to download the paid apps. But I can't even log in because of this "NeedsBrowser" error.

However, "registering a secondary account" from raccoon's interface *does* allow the account to interact with raccoon4.

@onyxbits , please fix this issue ;-;

**Comment by onyxbits** [comment]
Workaround: https://raccoon.onyxbits.de/blog/needs-browser-login-workaround/

**Comment by RandomBlbosti** [comment]
One way to also cheat this is by creating an app password and using that instead.

**Comment by zuloo** [comment]
Well the Workaround is probably only necessary to sell the PRO version of that software. You can not create a Market Profile without login, but the Workaround states to modify an existing one if you do not own the Pro Version. Since there is no Database to modify and no Documentation on the Schema this is just a rip off... Nice, I will just use ADB and download the App from a device then...

**Comment by tristan-k** [comment]
> Workaround: https://raccoon.onyxbits.de/blog/needs-browser-login-workaround/

I followed your instructions but I'm unable to save the database because I don't own a premium license. So because of the `NeedsBrowser` error it isn't possible to use Raccoon anymore without a license?

**Comment by im-izz** [comment]
> One way to also cheat this is by creating an app password and using that instead.

amazing, it still works

**Comment by capi1O** [comment]
> One way to also cheat this is by creating an app password and using that instead.

Quick way to do that is to go to https://myaccount.google.com/apppasswords

In my case no "app password" option was available in [Google Account](https://myaccount.google.com/) > Security > "Signing in to Google" even with 2FA enabled.

**Comment by masscream** [comment]
Looks like it does not work anymore, I created a pw and now i get UNKNOWN_ERR. Running 4.24.

<img width="528" height="383" alt="Image" src="https://github.com/user-attachments/assets/e6decb5e-e45e-4895-b576-3e42753e9c97" />

```
2026-03-09 13:43:19.355:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:34129
java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: UNKNOWN_ERR
	at de.onyxbits.raccoon.setup.LoginLogic.onDone(LoginLogic.java:138)
	at de.onyxbits.raccoon.setup.WizardWorker.done(WizardWorker.java:42)
	at java.desktop/javax.swing.SwingWorker$4.run(SwingWorker.java:749)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.apache.http.client.ClientProtocolException: UNKNOWN_ERR
	at com.akdeniz.googleplaycrawler.Identity.doPost(Identity.java:192)
	at com.akdeniz.googleplaycrawler.Identity.signIn(Identity.java:153)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.login(GooglePlayAPI.java:319)
	at de.onyxbits.raccoon.setup.LoginLogic.onDoInBackground(LoginLogic.java:88)
	at de.onyxbits.raccoon.setup.WizardWorker.doInBackground(WizardWorker.java:36)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:305)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:342)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

DummyDroid does not work either, throwing 400 Bad request, when entering the oauth_token.
