### ISSUE TITLE
Possible incompatibility with OpenJDK > 11.x on View -> My Apps

### ISSUE THREAD

**Issue by iasdeoupxe** [onyxbits/raccoon4#123]
Given three OpenJDK JRE versions running on Debian:

1. `openjdk 11.0.18 2023-01-17` (Updated to `11.0.23 2024-04-16` in the meantime)
2. `openjdk 17.0.6 2023-01-17` (Updated to `17.0.12 2024-07-16` in the meantime)
3. `openjdk 23-ea 2024-09-17`

Steps to reproduce:

1. Launch Racoon 4.24.0 with OpenJDK version `1` (via `java -jar raccoon-4.24.0.jar`)
2. Choose `View -> My Apps` (`F9`)
4. The app overview is showing up without any problem
5. Launch Racoon 4.24.0 with OpenJDK version `2` or `3` (via `java -jar raccoon-4.24.0.jar`)
6. Choose `View -> My Apps` (`F9`)
7. Nothing happens / app overview isn't showing up
8. In the console the error below is showing up

```
java.io.UncheckedIOException: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:120)
	at java.base/java.net.DatagramSocket.connect(DatagramSocket.java:474)
	at de.onyxbits.raccoon.net.ServerManager.whereIs(ServerManager.java:173)
	at de.onyxbits.raccoon.net.ServerManager.serve(ServerManager.java:69)
	at de.onyxbits.raccoon.appmgr.MyAppsViewBuilder.assemble(MyAppsViewBuilder.java:150)
	at de.onyxbits.weave.swing.AbstractPanelBuilder.build(AbstractPanelBuilder.java:56)
	at de.onyxbits.weave.swing.WindowBuilder.build(WindowBuilder.java:196)
	at de.onyxbits.raccoon.gui.MainLifecycle.onCreateSecondaryWindow(MainLifecycle.java:253)
	at de.onyxbits.weave.LifecycleManager.getWindow(LifecycleManager.java:119)
	at de.onyxbits.weave.swing.WindowToggleAction.toggleWindow(WindowToggleAction.java:77)
	at de.onyxbits.weave.swing.WindowToggleAction.actionPerformed(WindowToggleAction.java:70)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:411)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.net.SocketException: Can't connect to port 0
	at java.base/sun.nio.ch.DatagramChannelImpl.connect(DatagramChannelImpl.java:1239)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connectInternal(DatagramSocketAdaptor.java:91)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.connect(DatagramSocketAdaptor.java:118)
	... 47 more
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at de.onyxbits.weave.diag.ReportManager.render(ReportManager.java:183)
	at de.onyxbits.weave.diag.ReportBackend.capture(ReportBackend.java:64)
	at de.onyxbits.weave.diag.ReportManager.createBugReport(ReportManager.java:104)
	at de.onyxbits.weave.diag.ReportBackend.uncaughtException(ReportBackend.java:52)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1082)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1077)
	at java.desktop/java.awt.EventDispatchThread.processException(EventDispatchThread.java:222)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:214)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by iasdeoupxe** [comment]
Happens with the most recent OpenJDK version 23 also, adjusted description accordingly.

**Comment by jloehel** [comment]
It works with jdk-1.8 for me.

**Comment by iasdeoupxe** [comment]
Yes, everything <= 11.x should AFAICT work.
