### ISSUE TITLE
Cannot launch on Linux

### ISSUE THREAD

**Issue by msparkles** [onyxbits/raccoon4#131]
linux 6.12.6.arch1-1
jdk8-openjdk 8.432.u05-1
jdk17-openjdk 17.0.13.u11-1
jdk21-openjdk 21.0.5.u11-1
jdk-openjdk 23.0.1.u0-1

distro is arch linux, tried all the java versions installed as listed above.

```
Dec 28, 2024 10:10:53 AM org.hsqldb.persist.Logger logInfoEvent
INFO: checkpointClose start
Dec 28, 2024 10:10:53 AM org.hsqldb.persist.Logger logInfoEvent
INFO: checkpointClose synched
Dec 28, 2024 10:10:53 AM org.hsqldb.persist.Logger logInfoEvent
INFO: checkpointClose script done
Dec 28, 2024 10:10:53 AM org.hsqldb.persist.Logger logInfoEvent
INFO: checkpointClose end
java.lang.ExceptionInInitializerError
        at de.onyxbits.raccoon.gui.MainLifecycle.onCreatePrimaryWindow(MainLifecycle.java:189)
        at de.onyxbits.weave.LifecycleManager.getWindow(LifecycleManager.java:100)
        at de.onyxbits.weave.LifecycleManager.run(LifecycleManager.java:89)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException
        at java.base/java.util.Currency.getInstance(Currency.java:395)
        at de.onyxbits.raccoon.Bookmarks.<clinit>(Bookmarks.java:47)
        ... 16 more
```

and nothing after, no window is created.

**Comment by msparkles** [comment]
Unfortunately not
