### ISSUE TITLE
Systematically got the DF-DFERH-01 error

### ISSUE THREAD

**Issue by milouse** [onyxbits/raccoon4#20]
I've read your [blog post about it](http://blog.onyxbits.de/df-dferh-01-error-when-updating-apps-585/) [1] and reset my profile several time, but systematically the error come back.

I use Racoon only to download one paid app (I pay for it) because my phone do not have the play store (fairphone open AOSP).

This morning I try to update it, saw your warning about racoon 3 being deprecated. Thus I download the new version, and [follow the steps to import an existing app](http://blog.onyxbits.de/workaround-importing-apps-from-raccoon-v3-x-into-v4-x-580/). But nothing seems to work. In fact I see my imported app in the app manager, but I cannot find any other app (the search feature return 0 results, whatever I look for).

BTW, I use my main google account (but use it only for that…), which is protected by 2FA. During the configuration steps of racoon I disable 2FA, and enable it back as soon as I get the home view of racoon. Could this bug be linked with 2FA and app-specific password ?

I foolishly follow your tip in [1] and delete the Racoon 3 data file, thus I'm now stuck with a non-working racoon and no idea how to update my paid app :(

**Comment by onyxbits** [comment]
The only difference between v3 and v4 in that respect should be that v3 used username and password to obtain the auth cookie on program startup, whereas v4 only logs in during setup and then saves the auth cookie between sessions (kudos to everyone who kept nagging me about how unsecure storing a password is).

I think, reenabling 2FA might invalidate the auth cookie. Try disabling 2FA, setting up Raccoon v4 from scratch and see if everything works while 2FA is disabled. Once you are done, reenable 2FA and see if Raccoon stops working. If that's the case, then changing the 2FA setting kills the auth cookie.

**Comment by rancidfrog** [comment]
I am getting similar error when I try to Update apps imported from older content directory:
```
Caused by: com.akdeniz.googleplaycrawler.GooglePlayException: ?=Error while retrieving information from server. [DF-DFERH-01]J�
���晖���
Z�X
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:662)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:620)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePOSTRequest(GooglePlayAPI.java:576)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.bulkDetails(GooglePlayAPI.java:363)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.update(UpdateAppWorker.java:95)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.doInBackground(UpdateAppWorker.java:60)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.doInBackground(UpdateAppWorker.java:45)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-10-29 16:04:49.628:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/rsrc,null}
2017-10-29 16:04:49.628:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/files,null}
2017-10-29 16:04:49.628:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/app,null}
2017-10-29 16:04:49.629:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/apps,null}
```
Updating apps does not work. Searching always shows no result.
Using 4.1.6
I have 2FA disabled, and sometimes need to login to accounts.google.com and disable/enable 'Allow less secure apps' to login.

**Comment by rancidfrog** [comment]
```
java.util.concurrent.ExecutionException: com.akdeniz.googleplaycrawler.GooglePlayException: ?=Error while retrieving information from server. [DF-DFERH-01]J�
��������
���
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.done(UpdateAppWorker.java:121)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.akdeniz.googleplaycrawler.GooglePlayException: ?=Error while retrieving information from server. [DF-DFERH-01]J�
��������
���
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:662)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:620)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePOSTRequest(GooglePlayAPI.java:576)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.bulkDetails(GooglePlayAPI.java:363)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.update(UpdateAppWorker.java:95)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.doInBackground(UpdateAppWorker.java:60)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.doInBackground(UpdateAppWorker.java:45)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-10-29 16:18:51.362:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/rsrc,null}
2017-10-29 16:18:51.363:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/files,null}
2017-10-29 16:18:51.363:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/app,null}
2017-10-29 16:18:51.363:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/apps,null}
```

**Comment by onyxbits** [comment]
DF-DFERH-01]J indicates a problem with your device profile. In the setup wizard, did you let Raccoon generate the GSF ID or are you using a custom one?
rancidfrog <notifications@github.com> hat am 29. Oktober 2017 um 17:07 geschrieben:I am getting similar error when I try to Update apps imported from older content directory:
Caused by: com.akdeniz.googleplaycrawler.GooglePlayException: �?�=Error while retrieving information from server. [DF-DFERH-01]J����
���晖������
�Z��X��
 at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:662)
 at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:620)
 at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePOSTRequest(GooglePlayAPI.java:576)
 at com.akdeniz.googleplaycrawler.GooglePlayAPI.bulkDetails(GooglePlayAPI.java:363)
 at de.onyxbits.raccoon.gplay.UpdateAppWorker.update(UpdateAppWorker.java:95)
 at de.onyxbits.raccoon.gplay.UpdateAppWorker.doInBackground(UpdateAppWorker.java:60)
 at de.onyxbits.raccoon.gplay.UpdateAppWorker.doInBackground(UpdateAppWorker.java:45)
 at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at javax.swing.SwingWorker.run(SwingWorker.java:334)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
2017-10-29 16:04:49.628:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/rsrc,null}
2017-10-29 16:04:49.628:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/files,null}
2017-10-29 16:04:49.628:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/app,null}
2017-10-29 16:04:49.629:INFO:oejsh.ContextHandler:stopped o.e.j.s.h.ContextHandler{/apps,null}

Updating apps does not work. Searching always shows no result.
Using 4.1.6
I have 2FA disabled, and sometimes need to login to accounts.google.com and disable/enable 'Allow less secure apps' to login.

**Comment by rancidfrog** [comment]
I got one using dummydroid.
But, I just updated useragent by following http://blog.onyxbits.de/how-to-get-the-google-play-user-agent-for-a-given-device-140/
And updating app works now, but seach results still show no results.

Also, any clarification on:
@onyxbits `kudos to everyone who kept nagging me about how unsecure storing a password is`
It still has password in cleartext by the way - in `raccoondb_4.script`:
**INSERT INTO PLAYPROFILES VALUES('xxx','xxx','xxx','xxx',NULL,0,NULL,NULL,'xxx','PASSWORD_STORED_HERE')**

**Comment by rancidfrog** [comment]
Also, I get the same error again after importing all apps from previous content folder:
```
com.akdeniz.googleplaycrawler.GooglePlayException: ?=Error while retrieving information from server. [DF-DFERH-01]J�
�ҁ�������
��
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:662)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:620)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:599)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePOSTRequest(GooglePlayAPI.java:564)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.purchase(GooglePlayAPI.java:468)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.purchaseAndDeliver(GooglePlayAPI.java:439)
	at de.onyxbits.raccoon.gplay.AppDownloadWorker.onPrepare(AppDownloadWorker.java:174)
	at de.onyxbits.raccoon.transfer.Driver.transfer(Driver.java:152)
	at de.onyxbits.raccoon.transfer.Driver.run(Driver.java:87)
	at java.lang.Thread.run(Thread.java:748)
```
It seems there is a problem with `com.akdeniz.googleplaycrawler.GooglePlayException`
After going to **Market/Device/Edit** and reconnecting - it works again.
But I believe I will keep on having to do the same thing - reconnect after a while as I have the same problem with ApkUpdater using a different google account: https://github.com/rumboalla/apkupdater

**Comment by onyxbits** [comment]
> I got one using dummydroid.Stuff can go wrong there and it's usually beyond what I can help you with. That tool is intended for people who know what they are doing.> It still has password in cleartext by the wayNot still, but again:http://blog.onyxbits.de/the-password-dilemma-with-clientserver-applications-668/
rancidfrog <notifications@github.com> hat am 29. Oktober 2017 um 17:38 geschrieben:I got one using dummydroid.
But, I just updated useragent by following http://blog.onyxbits.de/how-to-get-the-google-play-user-agent-for-a-given-device-140/
And updating app works now, but seach results still show no results.
Also, any clarification on:
@onyxbits kudos to everyone who kept nagging me about how unsecure storing a password is
It still has password in cleartext by the way - in raccoondb_4.script:
INSERT INTO PLAYPROFILES VALUES('xxx','xxx','xxx','xxx',NULL,0,NULL,NULL,'xxx','PASSWORD_STORED_HERE')

**Comment by rancidfrog** [comment]
I got it to work. But, there is an issue as you know with google connection issues:
- https://github.com/yeriomin/YalpStore/issues/297
- https://github.com/yeriomin/YalpStore/issues/292
- https://github.com/rumboalla/apkupdater/issues/253

The issue is across all apps using google-api
For raccoon and apkUpdater, after login app works for a while but soon after error is thrown and the need to relogin.
