### ISSUE TITLE
BadAuthentication Error

### ISSUE THREAD

**Issue by Kasqade** [onyxbits/raccoon4#33]
After entering my account credentials and setting Raccoon up as a new device I am getting the error `Error=BadAuthentication`
Sometimes I am also getting a message that two-factor authentication may be enabled directly after entering the credentials, which is not true in my case.
I even tried to create a new Google Account but it had the same error.

Here is the full log:
`2017-06-03 17:50:18.267:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2017-06-03 17:50:18.366:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:36435
com.akdeniz.googleplaycrawler.GooglePlayException: Error=BadAuthentication
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:585)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:543)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:522)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.loginAC2DM(GooglePlayAPI.java:182)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.checkin(GooglePlayAPI.java:165)
	at de.onyxbits.raccoon.setup.UploadLogic.onDoInBackground(UploadLogic.java:89)
	at de.onyxbits.raccoon.setup.WizardWorker.doInBackground(WizardWorker.java:36)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

I am running Antergos Linux with JDK & JRE 8 installed

**Comment by onyxbits** [comment]
http://blog.onyxbits.de/and-google-broke-raccoon-again-2-625/

**Comment by Kasqade** [comment]
Oh okay, my fault. Didn't see that blog post there...

**Comment by yoghi** [comment]
It's possible now use "App password" 
_App passwords let you sign in to your Google Account from apps on devices that don't support 2-Step Verification. You'll only need to enter it once so you don't need to remember it. [Learn more](https://support.google.com/accounts/bin/answer/185833?hl=en)_ 

Create specific password for racoon and use that on it.
