### ISSUE TITLE
Error Message "Error retrieving information from server RH-02"

### ISSUE THREAD

**Issue by mr-jingles** [onyxbits/raccoon4#39]
Currently the connection to googleplaystore  closes with "Error retrieving information from server RH-02" and no Apps are shown.

**Comment by onyxbits** [comment]
I can't confirm that.

**Comment by mr-jingles** [comment]
I tried the following

- Different Google Account
- Emulated and existing device
- Downloaded and Github Version

I running on Ubuntu 16.04
with java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Here is the full Stacktrace:

2017-08-21 10:03:25.521:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:42714
java.lang.NullPointerException
	at de.onyxbits.raccoon.db.DatabaseManager.get(DatabaseManager.java:139)
	at de.onyxbits.raccoon.appmgr.MyAppsViewBuilder.assemble(MyAppsViewBuilder.java:197)
	at de.onyxbits.weave.swing.AbstractPanelBuilder.build(AbstractPanelBuilder.java:56)
	at de.onyxbits.weave.swing.WindowBuilder.build(WindowBuilder.java:196)
	at de.onyxbits.raccoon.gui.MainLifecycle.onCreateSecondaryWindow(MainLifecycle.java:249)
	at de.onyxbits.weave.LifecycleManager.getWindow(LifecycleManager.java:119)
	at de.onyxbits.weave.swing.WindowToggleAction.toggleWindow(WindowToggleAction.java:77)
	at de.onyxbits.weave.swing.WindowToggleAction.actionPerformed(WindowToggleAction.java:70)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at de.onyxbits.weave.diag.ReportManager.render(ReportManager.java:180)
	at de.onyxbits.weave.diag.ReportBackend.capture(ReportBackend.java:64)
	at de.onyxbits.weave.diag.ReportManager.createBugReport(ReportManager.java:104)
	at de.onyxbits.weave.diag.ReportBackend.uncaughtException(ReportBackend.java:52)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.util.concurrent.ExecutionException: com.akdeniz.googleplaycrawler.GooglePlayException: ;9Fehler beim Abrufen von Informationen vom Server: [RH-02]J�
���������
��
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.done(UpdateAppWorker.java:115)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.akdeniz.googleplaycrawler.GooglePlayException: ;9Fehler beim Abrufen von Informationen vom Server: [RH-02]J�
���������
��
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:652)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:610)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePOSTRequest(GooglePlayAPI.java:566)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.bulkDetails(GooglePlayAPI.java:363)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.update(UpdateAppWorker.java:89)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.doInBackground(UpdateAppWorker.java:60)
	at de.onyxbits.raccoon.gplay.UpdateAppWorker.doInBackground(UpdateAppWorker.java:45)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by onyxbits** [comment]
This is Update, not Search.

I think, Google deprecated the "bulk details" endpoint. I will look into this, once I'm done with rewriting the transfer subsystem.

**Comment by mr-jingles** [comment]
Sorry about that - I thought it was somehow related. Raccoon wont give me any search result no matter what I type into the search field. There is also no difference if a device is connected or not.

**Comment by onyxbits** [comment]
That usually happens if Play can't find compatible apps for the device you are currently using (e.g. if you simply made up a GSF ID or put something in the field you thought was a GSF ID, but isn't). Try setting up your profile again and let Raccoon generate a GSF ID for you.

**Comment by mr-jingles** [comment]
Something must have went wrong when I tried to retrieve the device data myself. A new pseudo device did the trick!
